# Generated by Django 3.2.7 on 2021-10-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_abbr', models.CharField(max_length=100)),
                ('course_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('description', models.CharField(max_length=500)),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.class')),
            ],
        ),
    ]
